# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sineWindowHW.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_sineWidgetWindow(object):
    def setupUi(self, sineWidgetWindow):
        sineWidgetWindow.setObjectName("sineWidgetWindow")
        sineWidgetWindow.resize(454, 414)
        self.centralwidget = QtWidgets.QWidget(sineWidgetWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.func_cmb = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.func_cmb.sizePolicy().hasHeightForWidth())
        self.func_cmb.setSizePolicy(sizePolicy)
        self.func_cmb.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.func_cmb.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.func_cmb.setEditable(False)
        self.func_cmb.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.func_cmb.setObjectName("func_cmb")
        self.func_cmb.addItem("")
        self.func_cmb.addItem("")
        self.func_cmb.addItem("")
        self.verticalLayout_2.addWidget(self.func_cmb)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.hgt_sld = QtWidgets.QSlider(self.centralwidget)
        self.hgt_sld.setMaximumSize(QtCore.QSize(16777000, 16777215))
        self.hgt_sld.setOrientation(QtCore.Qt.Horizontal)
        self.hgt_sld.setObjectName("hgt_sld")
        self.gridLayout.addWidget(self.hgt_sld, 1, 1, 1, 1)
        self.wdt_sld = QtWidgets.QSlider(self.centralwidget)
        self.wdt_sld.setMaximumSize(QtCore.QSize(16777000, 16777215))
        self.wdt_sld.setMaximum(25)
        self.wdt_sld.setPageStep(3)
        self.wdt_sld.setOrientation(QtCore.Qt.Horizontal)
        self.wdt_sld.setObjectName("wdt_sld")
        self.gridLayout.addWidget(self.wdt_sld, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.len_sld = QtWidgets.QSlider(self.centralwidget)
        self.len_sld.setMaximumSize(QtCore.QSize(16777000, 16777215))
        self.len_sld.setOrientation(QtCore.Qt.Horizontal)
        self.len_sld.setObjectName("len_sld")
        self.gridLayout.addWidget(self.len_sld, 0, 1, 1, 1)
        self.grid_sld = QtWidgets.QSlider(self.centralwidget)
        self.grid_sld.setMaximumSize(QtCore.QSize(16777000, 16777215))
        self.grid_sld.setMinimum(5)
        self.grid_sld.setOrientation(QtCore.Qt.Horizontal)
        self.grid_sld.setObjectName("grid_sld")
        self.gridLayout.addWidget(self.grid_sld, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.sine_ly = QtWidgets.QVBoxLayout()
        self.sine_ly.setObjectName("sine_ly")
        self.verticalLayout_2.addLayout(self.sine_ly)
        sineWidgetWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(sineWidgetWindow)
        self.grid_sld.valueChanged['int'].connect(self.label_8.setNum)
        self.wdt_sld.valueChanged['int'].connect(self.label_7.setNum)
        self.hgt_sld.valueChanged['int'].connect(self.label_6.setNum)
        self.len_sld.valueChanged['int'].connect(self.label_5.setNum)
        QtCore.QMetaObject.connectSlotsByName(sineWidgetWindow)

    def retranslateUi(self, sineWidgetWindow):
        _translate = QtCore.QCoreApplication.translate
        sineWidgetWindow.setWindowTitle(_translate("sineWidgetWindow", "MainWindow"))
        self.func_cmb.setItemText(0, _translate("sineWidgetWindow", "Sine"))
        self.func_cmb.setItemText(1, _translate("sineWidgetWindow", "Cosine"))
        self.func_cmb.setItemText(2, _translate("sineWidgetWindow", "Tangent"))
        self.label_7.setText(_translate("sineWidgetWindow", "1"))
        self.label_8.setText(_translate("sineWidgetWindow", "3"))
        self.label.setText(_translate("sineWidgetWindow", "    Length"))
        self.label_6.setText(_translate("sineWidgetWindow", "0"))
        self.label_5.setText(_translate("sineWidgetWindow", "0    "))
        self.label_4.setText(_translate("sineWidgetWindow", "Grid"))
        self.label_3.setText(_translate("sineWidgetWindow", "Width"))
        self.label_2.setText(_translate("sineWidgetWindow", "Height"))

