# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Марат\Desktop\Code\computeArea\computerArea.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_computeArea(object):
    def setupUi(self, computeArea):
        computeArea.setObjectName("computeArea")
        computeArea.resize(320, 276)
        self.centralwidget = QtWidgets.QWidget(computeArea)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.shape_cbb = QtWidgets.QComboBox(self.groupBox)
        self.shape_cbb.setObjectName("shape_cbb")
        self.shape_cbb.addItem("")
        self.shape_cbb.addItem("")
        self.verticalLayout.addWidget(self.shape_cbb)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.sq_gb = QtWidgets.QGroupBox(self.centralwidget)
        self.sq_gb.setObjectName("sq_gb")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sq_gb)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.sq_gb)
        self.label.setMinimumSize(QtCore.QSize(30, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sq_heigth_spx = QtWidgets.QSpinBox(self.sq_gb)
        self.sq_heigth_spx.setMaximum(99999999)
        self.sq_heigth_spx.setProperty("value", 10)
        self.sq_heigth_spx.setObjectName("sq_heigth_spx")
        self.horizontalLayout.addWidget(self.sq_heigth_spx)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.sq_gb)
        self.label_2.setMinimumSize(QtCore.QSize(30, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.sq_width_spx = QtWidgets.QSpinBox(self.sq_gb)
        self.sq_width_spx.setMaximum(99999999)
        self.sq_width_spx.setProperty("value", 10)
        self.sq_width_spx.setObjectName("sq_width_spx")
        self.horizontalLayout_2.addWidget(self.sq_width_spx)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.sq_gb)
        self.cr_gb = QtWidgets.QGroupBox(self.centralwidget)
        self.cr_gb.setObjectName("cr_gb")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.cr_gb)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.cr_gb)
        self.label_3.setMinimumSize(QtCore.QSize(30, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cr_radius_spx = QtWidgets.QSpinBox(self.cr_gb)
        self.cr_radius_spx.setMaximum(99999999)
        self.cr_radius_spx.setProperty("value", 10)
        self.cr_radius_spx.setObjectName("cr_radius_spx")
        self.horizontalLayout_3.addWidget(self.cr_radius_spx)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.cr_gb)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.compute_btn = QtWidgets.QPushButton(self.centralwidget)
        self.compute_btn.setObjectName("compute_btn")
        self.verticalLayout_3.addWidget(self.compute_btn)
        self.result_lb = QtWidgets.QLabel(self.centralwidget)
        self.result_lb.setObjectName("result_lb")
        self.verticalLayout_3.addWidget(self.result_lb)
        computeArea.setCentralWidget(self.centralwidget)

        self.retranslateUi(computeArea)
        QtCore.QMetaObject.connectSlotsByName(computeArea)

    def retranslateUi(self, computeArea):
        _translate = QtCore.QCoreApplication.translate
        computeArea.setWindowTitle(_translate("computeArea", "computeArea"))
        self.groupBox.setTitle(_translate("computeArea", "Select shape"))
        self.shape_cbb.setItemText(0, _translate("computeArea", "Square"))
        self.shape_cbb.setItemText(1, _translate("computeArea", "Circle"))
        self.sq_gb.setTitle(_translate("computeArea", "Square"))
        self.label.setText(_translate("computeArea", "Heght"))
        self.label_2.setText(_translate("computeArea", "Width"))
        self.cr_gb.setTitle(_translate("computeArea", "Circle"))
        self.label_3.setText(_translate("computeArea", "Radius"))
        self.compute_btn.setText(_translate("computeArea", "Compute"))
        self.result_lb.setText(_translate("computeArea", "Result"))

